### ISSUE TITLE
IndexError: Reached end of video

### ISSUE THREAD

**Issue by mrcolab** [dunnousername/yanderifier#10]
I have yanderify 3.0, every time I try to make a deepfake everything seems to be going fine, I click "Go", I wait for a while and then it gives me a crash message saying "IndexError: Reached end of video"
![image](https://user-images.githubusercontent.com/69219593/89344423-2876a200-d6a6-11ea-902e-d1cfc914e74b.png)
![image](https://user-images.githubusercontent.com/69219593/89344448-31677380-d6a6-11ea-84c3-4ac4357a00ae.png)

**Comment by mrcolab** [comment]
I was also running in CPU only mode

**Comment by mrcolab** [comment]
This issue doesn't happen in the version 2.0.5

**Comment by dunnousername** [comment]
This should be fixed in the latest alpha iirc.

**Comment by dunnousername** [comment]
I'm pretty sure this is solved in the latest stable. Feel free to reopen if you think this is still an issue, though.
