### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by rckidyt** [dunnousername/yanderifier#20]
Yanderify won't start when I double click the Start Yanderify shortcut.

My specs are a Ryzen 7 3800X and a GTX 1080 if that helps.

Here's a screen recording on OneDrive: https://1drv.ms/u/s!AqPX8RyglRZuqwzujiC8FzZqy6fO?e=5vf4XV

Sorry if I'm doing something wrong and just wasting your time, but I'm following a YouTube video...

**Comment by SerkanB422** [comment]
Have you solved your problem?

**Comment by rckidyt** [comment]
Yeah, I didn't extract it. Sorry for the confusion.
