### ISSUE TITLE
Stretching videos out after updating

### ISSUE THREAD

**Issue by Talkashie** [dunnousername/yanderifier#37]
Was previously using v2.0.5 and it was working great, but decided to update to see what was new. After updating to v4.0.2, all videos that I output are stretched out horizontally. I am using the exact same source files that I was in v2.0.5.

I also tried turning off the "relative" advanced option but that only broke things further.

For example, a video created in v2.0.5 was 528x640 resolution.
The same video made in v4.0.2 is 640x528. This results in the output being stretched horizontally. It looks like width and height are being flipped?

The source image is 518x639 and the source video is 256x256.

Not sure if it matters but I want to provide as much info as possible. My PC specs are:
Ryzen 9 3900X
32GB DDR4
RTX 2080 Super
Windows 10 1909

**Comment by Nontenda** [comment]
Same here. Some videos are completely resized horizontally.
