### ISSUE TITLE
i have another issue when i start the deep fake process it says that my pc isn't compatible with my pc version

### ISSUE THREAD

**Issue by KastroMugnaio** [dunnousername/yanderifier#57]
Error: received a OSError at stage "predict".
Message: "Could not load meta information
=== stderr ===

Accesso negato."
Full traceback:
  File "yanderify.py", line 211, in worker_thread

  File "imageio\core\functions.py", line 129, in get_reader

  File "imageio\core\format.py", line 168, in get_reader

  File "imageio\core\format.py", line 217, in __init__

  File "imageio\plugins\ffmpeg.py", line 358, in _open

  File "imageio\plugins\ffmpeg.py", line 523, in _load_infos

<log>
cpu=0
</log>
<inputs>
{C:/Users/gianp/Pictures/Baka Mitai deepfake template.mp4} {C:/Users/gianp/Videos/Desktop/Desktop Screenshot 2020.11.03 - 12.37.15.02.png} C:/Users/gianp/Pictures/bidoene.mp4
</inputs>

**Comment by encap** [comment]
I had the same problem on 4.0.3. Download "ffmpeg-win32-v3.2.4.exe" separately and paste it in "C:\Users\{your user name}\AppData\Local\imageio\ffmpeg\ffmpeg-win32-v3.2.4.exe". During the first run of yanderify this file is downloaded and can get corrupted.

**Comment by KastroMugnaio** [comment]
> I had the same problem on 4.0.3. Download "ffmpeg-win32-v3.2.4.exe" separately and paste it in "C:\Users{your user name}\AppData\Local\imageio\ffmpeg\ffmpeg-win32-v3.2.4.exe". During the first run of yanderify this file is downloaded and can get corrupted.

THANKS A LOT MAN

**Comment by dudbx** [comment]
encap的解决方法是可行的！
