### ISSUE TITLE
Fails to start at all when first Installing

### ISSUE THREAD

**Issue by Arburich** [dunnousername/yanderifier#6]
Hello! 

Newest version, 2.0.5, freshly downloaded. 

Moved it to a folder on the desktop, and it fails to run. I can't catch what it's saying either because there is a CMD prompt that opens up for barely a frame then closes again, so I can't tell you whats going wrong. 

I do have another python 3 installation on this system, so that *might* be the cause, but without debugging logs I can't really tell you!

**Comment by dunnousername** [comment]
Are you running the batch file? You need to run the shortcut instead or it'll immediately crash because it doesn't start in the right directory.

**Comment by Arburich** [comment]
Yeah, I tried both batches and both flash a CMD prompt on screen before exiting instantly.

**Comment by Arburich** [comment]
Er, sorry, shortcuts. I ran both shortcuts.

**Comment by sqiu0004** [comment]
Yep, same. I get **ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad'** before it closes.

**Comment by dunnousername** [comment]
Existing python installs seem to be causing issues for a lot of people. That said, I've actually installed python 3.8 and appended it to my PATH to do some testing. It appears to choose the right python version in the prerelease version of 3.0.0 through my initial testing if you'd like to check that out. Also, it's midnight here and I won't be able to provide additional support until I wake up. Feel free to try the prerelease version 3.0.0, though; a lot has changed, so there's a good chance the issue was fixed. You need to run the install shortcut and it'll gather all the dependencies. It might error out when trying to copy a file, but don't worry about that, it should be okay.

**Comment by Arburich** [comment]
Well at least this time I got an error error
```

Installing 64-bit...                                                                                                    starting post-install script
'C:\Users\4sonicride\Desktop\Cursed' is not recognized as an internal or external command,
operable program or batch file.
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\4sonicride\Desktop\Cursed Project\yanderify\yanderifier-master\install\windows\postinstall.ps1:1 char:1
+ conda init powershell
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\4sonicride\Desktop\Cursed Project\yanderify\yanderifier-master\install\windows\postinstall.ps1:2 char:1
+ conda env create -f environment.yml
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

cp : Cannot find path 'C:\Users\4sonicride\Desktop\Cursed
Project\yanderify\yanderifier-master\miniconda\Library\bin\libiomp5md.dll' because it does not exist.
At C:\Users\4sonicride\Desktop\Cursed Project\yanderify\yanderifier-master\install\windows\postinstall.ps1:4 char:1
+ cp miniconda\Library\bin\libiomp5md.dll miniconda\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\4sonic...\libiomp5md.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

cp : Cannot find path 'C:\Users\4sonicride\Desktop\Cursed Project\yanderify\yanderifier-master\miniconda\Library\bin'
because it does not exist.
At C:\Users\4sonicride\Desktop\Cursed Project\yanderify\yanderifier-master\install\windows\postinstall.ps1:5 char:1
+ cp miniconda\Library\bin\mkl_*.dll miniconda\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\4sonic...nda\Library\bin:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand


```

**Comment by dunnousername** [comment]
I think I fixed this in the latest alpha. My power went out so I was unable to push the changes, but it's back now.

**Comment by Arburich** [comment]
Can confirm my issue was solved at least. 

- Installed with installer
- everything ran as promised. 

Thanks for the awesome program! :)

**Comment by ayunami2000** [comment]
what i did was i just went to the two lines in the bat file that start with "cmd" and replaced "cmd" with "cmd.exe"
