### ISSUE TITLE
Crash when doing output

### ISSUE THREAD

**Issue by markiemm** [dunnousername/yanderifier#69]
Here is the whole log:

Started Yanderify 4.0.3-stable
Disclaimer: CPU mode on low-end computers or most laptops generally will cause the system to lock-up.
We are not liable if you freeze your PC by refusing to listen to this advice.
Written by dunnousername#8672.
heavily inspired by windy's efforts
New video input path: C:/Users/Markiemm/Videos/VID_20210127_160614.mp4
New image input path: C:/Users/Markiemm/Downloads/test.jpg
New video output path: C:/Users/Markiemm/Videos/trump test.mp4
starting...
Reloading checkpoints...
Finished reloading checkpoints
Loading sources...
Sources loaded
===========================
This section contains the details the devs need to fix this issue.
If you are reporting a bug, please include this entire section.
If you leave out any of it, there is a good chance the devs will not be able to help.
Error: received a RuntimeError at stage "predict".
Message: "inverse: For batch 0: U(446658560,446658560) is zero, singular U."
Full traceback:
  File "yanderify.py", line 229, in worker_thread

  File "yanderify.py", line 191, in make_animation_batch

  File "yanderify.py", line 172, in make_animation_batch_

  File "animate.py", line 33, in normalize_kp

<log>
cpu=0
</log>
<inputs>
C:/Users/Markiemm/Videos/VID_20210127_160614.mp4 C:/Users/Markiemm/Downloads/test.jpg {C:/Users/Markiemm/Videos/trump test.mp4}
</inputs>
This is the last line of the crash report section.
===========================
yanderify crashed!
some common problems:
- you have an AMD card. AMD cards are not supported in GPU mode for technical reasons. However, you can run in CPU mode, albeit much lower. Please read the disclaimer at the top about CPUs!
- you have an NVIDIA card, but there is either not enough VRAM or the card is too old. >=700-series cards with >=2GB dedicated VRAM should work fine
- you have a working card, but there is not enough available VRAM to run the deepfake process. Browsers commonly cause VRAM issues. If you have any games open, try closing them.
- one of the devs fucked up somewhere. if that is the case, make sure to submit the full crash report (you might have to scroll up!), otherwise we cannot help you!

**Comment by Animan8000** [comment]
What GPU?

**Comment by markiemm** [comment]
> Which GPU has been used?

RTX 3070

**Comment by Animan8000** [comment]
RTX 30XX GPUs are not supported unfortunately. They're using a new CUDA version which isn't compatible with one or several used dependencies. You would need to use CPU mode instead ("I don't have NVIDIA >= GTX750" checkbox).

**Comment by markiemm** [comment]
> RTX 30XX GPUs are not supported unfortunately. They're using a new CUDA version which isn't compatible with one or several used dependencies. You would need to use CPU mode instead ("I don't have NVIDIA >= GTX750" checkbox).

Ah ok, thanks for the reply
