### ISSUE TITLE
[question]how to select a video in 5.0.0 alpha 0 version?

### ISSUE THREAD

**Issue by SekiBetu** [dunnousername/yanderifier#70]
![image](https://user-images.githubusercontent.com/38283893/106705117-4d81a880-6628-11eb-806e-1e58aecbd90e.png)
no window showed, keyboard not working

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/106705683-5de65300-6629-11eb-8332-48adccada4f7.png)
oh, my bad, just click the exe, it works, i thought it can be running in Windows Terminal

**Comment by SekiBetu** [comment]
btw, vcruntime140_cor3.dll and wpfgfx_cor3.dll (from .NET5.0.2) are required to run this program, which is not included in the release zip file, maybe it's because of some license troubles?

**Comment by Animan8000** [comment]
No, it just has been forgotten accidentally. Will be fixed in the next release!
